[variables]
PORT = "8080"
PYTHON_VERSION = "3.12"
NODE_VERSION = "18"

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend"
]

[phases.start]
cmd = "./start.sh"
